// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Setup Guides',
      items: [{type: 'autogenerated', dirName: 'setup'}],
    },
    {
      type: 'category',
      label: 'Module 1: ROS 2',
      items: [{type: 'autogenerated', dirName: 'module-1-ros-2'}],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twin',
      items: [{type: 'autogenerated', dirName: 'module-2-digital-twin'}],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac',
      items: [{type: 'autogenerated', dirName: 'module-3-nvidia-isaac'}],
    },
    {
      type: 'category',
      label: 'Module 4: VLA & Humanoids',
      items: [{type: 'autogenerated', dirName: 'module-4-vla-humanoids'}],
    },
    'assessments-and-exercises',
    'deployment-and-validation',
    'glossary',
  ],
};

export default sidebars;
